# Generated by Django 2.2.12 on 2020-06-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='updated_domain',
            field=models.CharField(blank=True, db_index=True, max_length=253, null='True', unique=True),
            preserve_default='True',
        ),
    ]
