# Generated by Django 2.2.12 on 2020-06-11 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200610_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='updated_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='teacher.Domain'),
        ),
    ]
