# Generated by Django 2.2.12 on 2020-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20200611_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='updated_domain',
        ),
        migrations.AddField(
            model_name='domain',
            name='visit_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
