# Generated by Django 2.2.12 on 2020-06-06 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
    ]
