# Generated by Django 2.2.12 on 2020-06-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cschool',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='cschool',
            name='subtitle',
            field=models.CharField(blank=True, default='yours scool subtitle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cschool',
            name='title',
            field=models.CharField(blank=True, default='yours scool title', max_length=100, null=True),
        ),
    ]
