# Generated by Django 2.2.12 on 2020-06-17 20:03

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200617_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='footer',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='customize',
            name='navbar',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
