# Generated by Django 2.2.12 on 2020-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20200618_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='customize',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customize',
            name='homepageimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customize',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
